version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  
  
  #  dotnet-api:
#    container_name: dotnet-api
#    image: thijmentang/showcase-backend-api
#    environment:
#      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mssql
#    networks:
#      - app-network
#  frontend-react:
#    container_name: react-frontend
#    image: thijmentang/showcase-backend-api
#    environment:
#      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mssql
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
    name: showcase-backend