version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  
  showcase-backend:
    container_name: showcase-backend
    
    build:
      context: ./DotNetAuth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"            # match Kestrel port
    depends_on:
      - postgres
    environment:
      # Ensure Kestrel listens on container port 8080
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres-db;Database= ${POSTGRES_DB:-appdb};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
